apiVersion: v1
kind: ConfigMap
metadata:
  name: env-backend
  namespace: secure-app
data:
  MONGO_IP: 'mongodb://mongo-0.mongo.sample-app.svc.cluster.local,mongo-1.mongo.sample-app.svc.cluster.local.mongo,mongo-2.mongo.sample-app.svc.cluster.local:27017/'
