apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-todo-ingress
  namespace: secure-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/tls-acme: "false"
spec:
 rules:
 - host: *
   http:
     paths:
     - path: /
       backend:
           serviceName: python-todo-service
           servicePort: 80
