apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - python
        - -u
        - app.py
        env:
        - name: MONGO_IP
          value: '{{db|container_hostname}}'
        image: dchq/docker-python:latest
        name: web
        resources: {}
      restartPolicy: Always
status: {}
